### ISSUE TITLE
Unhandled error after 'cerebral' package adding

### ISSUE THREAD

**Issue by hipertracker** [cerebral/cerebral#1078]
I can't run tests after Cerebral is installed.

```
create-react-app my-app --scripts-version custom-react-scripts
cd my-app
yarn test
```

All works fine, but...

```
yarn add cerebral
yarn test 
 RUNS  src/App.test.js
 RUNS  src/App.test.js
2017-09-08 14:33 node[26504] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: Error watching file for changes: EMFILE
    at _errnoException (util.js:1041:11)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1359:9)
```

This bug can be reproduced in both The current and the LTS Node version.

**Comment by hipertracker** [comment]
It was described at https://github.com/facebookincubator/create-react-app/issues/871. The problem is gone after brew update; brew install watchman
