### ISSUE TITLE
improve error reporting modules.signals() empty call

### ISSUE THREAD

**Issue by Guria** [cerebral/cerebral#180]
> I by accident did a module.signals(); and gives crazy non-describe error stack.  might need a check to stop bad devs 😛

**Comment by christianalfoni** [comment]
I am thinking about an "error and optimization" hackathon. Maybe dedicate our meetup in July to this, like, not everyone... but those who wants to get an insight into how Cerebral works. It would be a great result after the weekend. And an important step to get to 1.0. There are lots of production optimizations that can be done, and error reporting.

**Comment by saulshanabrook** [comment]
The error trace for this isn't that bad and points to the right line, even if it isn't as descriptive as it could be:

```
TypeError: Object.keys called on non-object
    at Function.keys (native)
    at registerSignals (/Users/saul/projects/cerebral/src/CreateRegisterModules.js:7:32)
    at ctrl.addModules.test (/Users/saul/projects/cerebral/tests/modules.js:80:14)
    at registerModule (/Users/saul/projects/cerebral/src/CreateRegisterModules.js:84:29)
    at /Users/saul/projects/cerebral/src/CreateRegisterModules.js:42:7
    at Array.forEach (native)
    at EventEmitter.registerModules [as addModules] (/Users/saul/projects/cerebral/src/CreateRegisterModules.js:41:26)
    at Object.suite.should fail on no signals (/Users/saul/projects/cerebral/tests/modules.js:78:8)
    at Object.<anonymous> (/Users/saul/projects/cerebral/node_modules/nodeunit/lib/core.js:236:16)
    at Object.<anonymous> (/Users/saul/projects/cerebral/node_modules/nodeunit/lib/core.js:236:16)
``` 

Where `/Users/saul/projects/cerebral/tests/modules.js:80` is `module.addSignals()`.

I am closing this for now, since I think this is relatively understandable. A more comprehensive solution would be to properly check the types of all inputs to Cerebral functions, but this would require something like tcomb for runtime checks or Typescript for compile time checks. If either of those things happen, this will be resolved as a byproduct anyway. Feel free to reopen if you feel like this stack trace is unintelligible
