### ISSUE TITLE
bug(function-tree): TypeError: Cannot read property 'color' of null

### ISSUE THREAD

**Issue by ericclemmons** [cerebral/cerebral#366]
Given:

``` js
const FunctionTree = require('function-tree')
const NodeDebuggerProvider = require('function-tree/providers/NodeDebugger')
const ContextProvider = require('function-tree/providers/Context')
const express = require("express");

const app = express().get("/", (req, res) => res.send("howdy!"));

const run = new FunctionTree([
  // Verified this is the problem
  NodeDebuggerProvider({ colors: { app: "green" } }),
  ContextProvider({ app })
]);

const startServer = (context) => new Promise((resolve, reject) => {
  const { app, path } = context;

  const server = app.listen(3000, (error) => {
    if (!path) {
      return console.log(`Listening on 3000...`);
    }

    return error ? reject(path.error({ error })) : resolve(path.success({ server }));
  });
});

const stopServer = (context) => new Promise((resolve, reject) => {
  const { app, input, path } = context;

  input.server.close((error) => {
    return error ? reject(path.error({ error })) : resolve(path.success());
  });
});

run([ startServer, {
  success: [stopServer, {
    success: [startServer],
  }],
}]);

```

An error in `NodeDebuggerProvider` occurs:

``` shell
❯ node index.js
 => new Promise
{}
app.listen 3000
 => new Promise
{"server":{"domain":null,"_events":{},"_eventsCount":2,"_connections":0,"_handle":{"bytesRead":0,"_externalStream":{},"fd":13,"reading":false,"owner":"[CIRCULAR]","onread":null,"writeQueueSize":0},"_usingSlaves":false,"_slaves":[],"_unref":false,"allowHalfOpen":true,"pauseOnConnect":false,"httpAl...
events.js:160
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'color' of null
    at send (/Users/Eric/tmp/f-express/node_modules/function-tree/providers/NodeDebugger.js:86:27)
    at /Users/Eric/tmp/f-express/node_modules/function-tree/providers/NodeDebugger.js:145:5
    at /Users/Eric/tmp/f-express/node_modules/function-tree/src/index.js:119:9
    at Array.reduce (native)
    at FunctionTreeExecution.createContext (/Users/Eric/tmp/f-express/node_modules/function-tree/src/index.js:116:48)
    at FunctionTreeExecution.runFunction (/Users/Eric/tmp/f-express/node_modules/function-tree/src/index.js:40:24)
    at runBranch (/Users/Eric/tmp/f-express/node_modules/function-tree/src/executeTree.js:41:7)
    at /Users/Eric/tmp/f-express/node_modules/function-tree/src/executeTree.js:18:13
    at /Users/Eric/tmp/f-express/node_modules/function-tree/src/index.js:58:11
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

Converting `NodeDebuggerProvider.js` at Line 82 from:

``` js
    if (isExistingFunction) {

      var data = prevFunction.data[prevFunction.data.length - 1]
      var args = data ? data.args || [] : []
```

to

```
    if (isExistingFunction) {

      var data = prevFunction.data[prevFunction.data.length - 1] || {};
      var args = data ? data.args || [] : []
```

resolves it, but returns `undefined`, which is clearly not desirable:

``` shell
❯ node index.js
 => new Promise
{}
app.listen 3000
 => new Promise
{"server":{"domain":null,"_events":{},"_eventsCount":2,"_connections":0,"_handle":{"bytesRead":0,"_externalStream":{},"fd":13,"reading":false,"owner":"[CIRCULAR]","onread":null,"writeQueueSize":0},"_usingSlaves":false,"_slaves":[],"_unref":false,"allowHalfOpen":true,"pauseOnConnect":false,"httpAl...
undefined
app.listen 3000
Listening on 3000...
```

**Comment by TomKaltz** [comment]
Yeah I had this same problem with the node debugger.

**Comment by Guria** [comment]
Thanks for report, will check it out

**Comment by ericclemmons** [comment]
I hope the code samples help!

**Comment by Guria** [comment]
Sorry guys for delay. Now when repo has a great setup, could one of you prepare PR with failing test?

**Comment by ericclemmons** [comment]
Hmmm, I don't know how to go about a test for that since this was a run-time, integration-style bug.

**Comment by henri-hulski** [comment]
Could you try it with the current master? 
We switched to EventEmitter3 (#407) so maybe something changed.

**Comment by christianalfoni** [comment]
Closing this as we have new function tree that can be used with cerebral debugger
