### ISSUE TITLE
error in devtools when signals occur before websocket probing finished

### ISSUE THREAD

**Issue by Guria** [cerebral/cerebral#637]
```
index.js:297Uncaught DOMException: Failed to execute 'send' on 'WebSocket': Still in CONNECTING state.
    at Devtools.sendMessage (http://cerebral-guria.c9users.io:8080/static/js/bundle.js:35455:18)
    at Devtools.sendComponentsMap (http://cerebral-guria.c9users.io:8080/static/js/bundle.js:35766:13)
    at later (http://cerebral-guria.c9users.io:8080/static/js/bundle.js:33208:13)
sendMessage @ index.js:297
sendComponentsMap @ index.js:608
later @ utils.js:138
setTimeout (async)
(anonymous) @ utils.js:142
updateComponents @ Controller.js:189
flush @ Controller.js:160
(anonymous) @ Controller.js:121
emit @ index.js:151
(anonymous) @ index.js:282
runBranch @ executeTree.js:42
runNextItem @ executeTree.js:14
(anonymous) @ executeTree.js:31
runFunction @ index.js:173
runBranch @ executeTree.js:61
executeTree @ executeTree.js:65
runTree @ index.js:271
runSignal @ Controller.js:241
currentSignals.(anonymous function) @ Module.js:27
onChange @ index.js:21
executeOnChange @ LinkedValueUtils.js:129
_handleChange @ ReactDOMInput.js:232
ReactErrorUtils.invokeGuardedCallback @ ReactErrorUtils.js:70
executeDispatch @ EventPluginUtils.js:85
executeDispatchesInOrder @ EventPluginUtils.js:108
executeDispatchesAndRelease @ EventPluginHub.js:43
executeDispatchesAndReleaseTopLevel @ EventPluginHub.js:54
forEachAccumulated @ forEachAccumulated.js:24
processEventQueue @ EventPluginHub.js:257
runEventQueueInBatch @ ReactEventEmitterMixin.js:17
handleTopLevel @ ReactEventEmitterMixin.js:28
handleTopLevelImpl @ ReactEventListener.js:72
perform @ Transaction.js:140
batchedUpdates @ ReactDefaultBatchingStrategy.js:62
batchedUpdates @ ReactUpdates.js:97
dispatchEvent @ ReactEventListener.js:147
index.js:297 Uncaught DOMException: Failed to execute 'send' on 'WebSocket': Still in CONNECTING state.
    at Devtools.sendMessage (http://cerebral-guria.c9users.io:8080/static/js/bundle.js:35455:18)
    at Devtools.sendComponentsMap (http://cerebral-guria.c9users.io:8080/static/js/bundle.js:35766:13)
    at later (http://cerebral-guria.c9users.io:8080/static/js/bundle.js:33208:13)
sendMessage @ index.js:297
sendComponentsMap @ index.js:608
later @ utils.js:138
setTimeout (async)
(anonymous) @ utils.js:142
updateComponents @ Controller.js:189
flush @ Controller.js:160
(anonymous) @ Controller.js:121
emit @ index.js:151
(anonymous) @ index.js:282
runBranch @ executeTree.js:42
runNextItem @ executeTree.js:14
(anonymous) @ executeTree.js:31
runFunction @ index.js:173
runBranch @ executeTree.js:61
executeTree @ executeTree.js:65
runTree @ index.js:271
runSignal @ Controller.js:241
currentSignals.(anonymous function) @ Module.js:27
onChange @ index.js:21
executeOnChange @ LinkedValueUtils.js:129
_handleChange @ ReactDOMInput.js:232
ReactErrorUtils.invokeGuardedCallback @ ReactErrorUtils.js:70
executeDispatch @ EventPluginUtils.js:85
executeDispatchesInOrder @ EventPluginUtils.js:108
executeDispatchesAndRelease @ EventPluginHub.js:43
executeDispatchesAndReleaseTopLevel @ EventPluginHub.js:54
forEachAccumulated @ forEachAccumulated.js:24
processEventQueue @ EventPluginHub.js:257
runEventQueueInBatch @ ReactEventEmitterMixin.js:17
handleTopLevel @ ReactEventEmitterMixin.js:28
handleTopLevelImpl @ ReactEventListener.js:72
perform @ Transaction.js:140
batchedUpdates @ ReactDefaultBatchingStrategy.js:62
batchedUpdates @ ReactUpdates.js:97
dispatchEvent @ ReactEventListener.js:147
index.js:145 WebSocket connection to 'ws://localhost:8787/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
addListeners @ index.js:145
init @ index.js:215
Controller @ Controller.js:128
exports.default @ Controller.js:14
(anonymous) @ controller.js:8
__webpack_require__ @ bootstrap 7c58f3d…:555
fn @ bootstrap 7c58f3d…:86
(anonymous) @ index.js:3
__webpack_require__ @ bootstrap 7c58f3d…:555
fn @ bootstrap 7c58f3d…:86
(anonymous) @ bootstrap 7c58f3d…:578
__webpack_require__ @ bootstrap 7c58f3d…:555
(anonymous) @ bootstrap 7c58f3d…:578
(anonymous) @ bootstrap 7c58f3d…:578
index.js:223 You have configured remoteDebugger, but could not connect. Falling back to Chrome extension
```

**Comment by christianalfoni** [comment]
When it is probing it should put it into the backlog... pretty sure this is working now. You know how to provoke it?

**Comment by edgesoft** [comment]
@Guria @christianalfoni Is this solved? Maybe we can close this?
